algolia/search-insights.js

- lib/__tests__/harvest.test.ts
- package.json
- server/server.js
I noticed the server was started almost manually before calling jest et not properly stopped after tests have finished.
I think a proper way would be to start and stop the server in beforeAll/afterAll hooks.
This is what this PR is doing.
We can write more tests now and now mode EADDRINUSE when running tests twice
> fix(tests): properly start/stop testServer

- examples/async/async.js
- examples/helper/helper.js
- examples/instantsearch/instantsearchExample.js
- examples/lunr/lunr.js
- examples/react-instantsearch/src/App.js
- lib/__tests__/_sendEvent.test.ts
- lib/__tests__/click.test.ts
- lib/__tests__/conversion.test.ts
- lib/__tests__/harvest.test.ts
- lib/__tests__/init.test.ts
- lib/_cookieUtils.ts
- lib/_sendEvent.ts
- lib/click.ts
- lib/conversion.ts
- lib/init.ts
- lib/insights.ts
- lib/view.ts
- rollup.config.js
Target story:
> A developer should be able to choose the region he/she wants to use to send events
In the last PR https://github.com/algolia/search-insights.js/pull/40 we introduce region param and compute the endpoint origin.
In this PR, we use the endpoint.
i've also removed the process.env.NODE_ENV check from the codebase (partly addressing #23)
> feat(region): use region based endpoint

- examples/async/async.js
- examples/helper/helper.js
- examples/instantsearch/instantsearchExample.js
- examples/lunr/lunr.js
- examples/react-instantsearch/src/App.js
- lib/__tests__/_sendEvent.test.ts
- lib/__tests__/click.test.ts
- lib/__tests__/conversion.test.ts
- lib/__tests__/harvest.test.ts
- lib/__tests__/init.test.ts
- lib/_cookieUtils.ts
- lib/_sendEvent.ts
- lib/click.ts
- lib/conversion.ts
- lib/init.ts
- lib/insights.ts
- lib/view.ts
- rollup.config.js
Target story:
> A developer should be able to choose the region he/she wants to use to send events
- we introduce region param
- compute endpointOrigin, but it's still unsued 
will start using it in next PR (there are too tests to migrate so best done in a separate PR)
> feat(init): introduce region param and compute endpointOrigin

- config/webpack.config.js
Just released 0.0.16.
When NODE_ENV=production examples are compiled to use a specific version on the CDN.
This PR updates the examples to use `~0.0.16`.
I would have used `^0.0.16` but oddly enough the CDN does not return `0.0.16` in that case
> chore(examples): update to 0.0.16

- lib/__tests__/_sendEvent.test.ts
- lib/__tests__/harvest.test.ts
- lib/_sendEvent.ts
- lib/click.ts
- lib/conversion.ts
- lib/view.ts
This PR is a port of the fix that was made on 0.0.15.
It aims to allow the user not to send a timestamp in order to use the server-side generated timestamp.
User can still override the timestamp if wanted
fixes #46
fixes #32
> fix(timestamp): make timestamp optional

- lib/__tests__/_processQueue.test.ts
- lib/_processQueue.ts
- lib/insights.ts
This is adding some tests for processQueue which was untested until now.
I'm going to change it, so I'm preparing for it.
> fix(processQueue): extract globalObject from processQueue for easier testing

- .travis.yml
- package.json
- tsconfig.json
This adds a command that compiles the typescript code and checks the
types.
It is similar to the one that can be found in instantsearch.js:
https://github.com/algolia/instantsearch.js/blame/b3c2154d19bb8e50a07bdd0d5272eb8e3911279e/package.json#L34-L35
**UPDATE:**
pr build is breaking because of a rollup issue I located in the replace plugin.
The plugin has been remove here: https://github.com/algolia/search-insights.js/pull/113
This PR should build when the removal is live on develop.
> chore(tsc): add type-check for cmdline and CI

- lib/insights.ts
- tsconfig.json
⚠️ this is to be merged after https://github.com/algolia/search-insights.js/pull/111
This is the new way for catching unsued variable or imports.
It used to be something handle on tslint level but the [`no-unused-variable`](https://palantir.github.io/tslint/rules/no-unused-variable/) rule has been deprecated since tslint@5.11.0: see https://github.com/palantir/tslint/blob/master/CHANGELOG.md#warning-deprecations.
fixes #62 
I had to opt-out of the following settings:
**noImplicitThis**
Adopting this one requires (at least) changes in every method.
At the moment, the main class AlgoliaAnalytics is split accross multiples files. Each method has is own file, more or less.
```ts
// in _sendEvent.ts
function sendEvent(params: any) {
// reference to `this` is implicit
}
// in insights.ts
class …
```
> chores(tooling): enable noUnusedLocals and strict

- lib/__tests__/_cookieUtils.test.ts
- lib/_cookieUtils.ts
**Summary** 
This makes the `getCookie()` not fail if the client happens to have malformed cookies we can't decode.
- decode only cookie of interest (cname cookie) rather than the whole
document.cookie string
- wrap decoding a try catch and return empty cookie with a warning.
NB: this is currently going to `0.x` (used on Magento 1 Algolia bundle).
I'll likely have to backport this to the dev branch and release it on `1.x`, although nobody complained about it so far.
> fix(getCookie): support malformed cookie strings

- examples/instantsearch/instantsearchExample.js
This fixes a bug of the example on IE10.
Since IE10 does not have `elem.matches()` function, it patches with `elem.msMatchesSelector()`.
> chore: fix a bug of the example on IE10

- config/webpack.config.js
This PR updates `SCRIPT_SRC` for dev environment.
The host could be other than `localhost:8080`.
For example, when using [Serveo](https://serveo.net/) to test local build on BrowserStack, it tried to load `http://localhost:8080/search-insights.min.js` file and failed.
After this fix, it loads the js file relatively to the current host.
> chore: update SCRIPT_SRC for dev environment

- lib/_cookieUtils.ts
This PR removes `startWith` from `_cookieUtils.ts`. It was throwing an error in IE10.
After this fix, I've confirmed it's working fine in BrowserStack.
> fix: remove startWith and use indexOf instead

- .env.example
- .gitignore
- config/webpack.config.js
- package.json
- yarn.lock
This PR adds `dotenv` to devDependencies.
Instead of running `NODE_ENV=production INDEX_NAME=xxx APP_ID=yyy API_KEY=zzz yarn dev` every time,
we can create a file `.env` and put the following as the content:
```
NODE_ENV=production
INDEX_NAME=xxx
APP_ID=yyy
API_KEY=zzz
```
`.env` is included in `.gitignore`, so won't be commited, but used only locally.
> chore: add dotenv

- lib/__tests__/_processQueue.test.ts
- lib/_processQueue.ts
Reassigning the pointer is a bad idea &mdash; see https://github.com/algolia/search-insights.js/issues/127. It's causing issues when `window.aa` is passed to InstantSearch or anything using it too early (before the library loaded)
This is a fix that doesn't require to change the install snippet. 
If you have a better idea, please let me know 😄 
fixes #127
> fix(bug): persist function reference after library is loaded

- package.json
- yarn.lock
This PR adds [typeahead](https://github.com/jest-community/jest-watch-typeahead) plugin to jest.
> chore: add jest watch typeahead plugin

- .travis.yml
This PR updates Travis config regarding xvfb.
Their documentation now tells us to change the syntax.
- https://benlimmer.com/2019/01/14/travis-ci-xvfb/
- https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
> chore: update travis config regarding xvfb

- MIGRATION.md
- README.md
- package.json
This is a rewrite of the documentation in the README to be clearer about the use cases and the API.
- The getting started is more clear
- The options are more exhaustive
- The use cases are better explained (search analytics / personalization)
- The migration guide is moved to its own file
[View rendered →](https://github.com/algolia/search-insights.js/blob/6a83fa41f25720058829c3343d9994d0caef46c6/README.md)
> docs(readme): update documentation

- README.md
The `positions` passed in events (`clickedObjectIDsAfterSearch`) are numbers, not strings.
> docs(readme): convert `positions` to numbers

- CHANGELOG.md
- package.json
- yarn.lock
This PR adds `CHANGELOG.md` and a script to automatically update it.
`yarn changelog` will update the `CHANGELOG.md` file, considering the lastly released version (git tag).
`yarn changelog` will be added to the release process later.
Rendered [CHANGELOG.md](https://github.com/algolia/search-insights.js/blob/751036657fe92b886511329baf1407260702dc32/CHANGELOG.md)
> chore: add changelog

- .travis.yml
- package.json
- ship.config.js
- yarn.lock
This PR updates the version of `Ship.js` to the latest.
Its command `shipjs release` has been renamed to `shipjs trigger`
and a few bugs have been fixed.
This also configures Ship.js to auto-assign `@algolia/instantsearch-for-websites` team when creating a PR.
> chore: update release script

- lib/__tests__/_cookieUtils.test.ts
- lib/_cookieUtils.ts
Since all the characters we are using are equal to their encoded
version, encoding/decoding is not necessary.
Also removed the test checking the bahviour in the unlikely
situation of having a malformed ALOGLIA cookie value.
This ports fix: #125 on 1.x
>  fix(getCookie): support malformed cookie strings

- gtm/README.md
This alternative closes #173 by linking to the [official documentation](https://www.algolia.com/doc/guides/getting-insights-and-analytics/connectors/google-tag-manager/) that is now available on the Algolia website.
> docs(gtm): link to the official documentation

- .gitignore
- .travis.yml
- package.json
- ship.config.js
- yarn.lock
This PR adds Ship.js to `v0` branch.
The config is almost the same with the one from `master`.
> chore: add ship.js as a release tool to v0

- lib/insights.ts
This remove `?` on the parameter `param`. It's rather a typo fix.
CI runs the type-check job which will ensure this compiles.
This closes: https://github.com/algolia/search-insights.js/issues/53
> fix(types): remove optional types on main methods

- .env.example
- package.json
This PR removes unnecessary `NODE_ENV=production` from `.env.example`.
> chore: remove NODE_ENV from .env.example

- lib/__tests__/_sendEvent.test.ts
- lib/_sendEvent.ts
The existing request functions return undefined, so this isn't a breaking change, but this allows you to have a custom requester you can wait on (e.g. fetch).
fixes #199
> feat(sendEvent): return the value of the request function

- package.json
This PR removes `browser` key from `package.json`.
When `search-insights` is loaded by `require` or `import`, umd version is still loaded because of `browser`.
- before this PR: https://codesandbox.io/s/wonderful-sammet-s2p7k?file=/src/index.js
- in this PR: https://codesandbox.io/s/vibrant-antonelli-wv3zr?file=/src/index.js
cjs build [exports a function](https://github.com/algolia/search-insights.js/blob/chore/remove-browser/lib/node.ts#L9:L9), but if you try with "before this PR" sandbox, you can see an object is imported (which means it's a umd build).
I also downloaded the sandbox and modified the dist/ files to see which one is loaded, to make sure.
I guess it's safe to remove `browser`, because we specifically guide to use `jsdeliver` in case of umd and we don't have `browser` in …
> chore: remove browser from package.json

- README.md
This PR adds the usage of `createInsightsClient` for node env.
> docs: add usage of createInsightsClient for node env

- README.md
- lib/browser.ts
- lib/node.ts
This was made in parallel to the node implementation
@eunjae-lee, do you know why the `getFunctionalInterface` isn't used in the browser?
> feat(browser): expose createInsightsClient

- README.md
We moved the GTM integration to its own repo but the link wasn't updated.
> docs(readme): update link to GTM custom template

- README.md
- lib/__tests__/init.test.ts
- lib/_cookieUtils.ts
- lib/insights.ts
This PR adds `onUserTokenChange` so that you can attach a callback to receive user token changes.
> feat: add onUserTokenChange to know when token is assigned

- lib/__tests__/harvest.test.ts
- lib/browser.ts
This PR fixes the browser bundle. 
1. It didn't return `instance`
2. Now it's exporting the mix of default and named variables, so we need to use `window.AlgoliaAnalytics.default` instead of `window.AlgoliaAnalytics` in the e2e test.
On the user-side, they don't need to care about `.default` because all they use is `window.aa` which is created by the snippet:
```html
<script>
var ALGOLIA_INSIGHTS_SRC = "https://cdn.jsdelivr.net/npm/search-insights@1.4.0";
!function(e,a,t,n,s,i,c){e.AlgoliaAnalyticsObject=s,e[s]=e[s]||function(){
(e[s].queue=e[s].queue||[]).push(arguments)},i=a.createElement(t),c=a.getElementsByTagName(t)[0],
i.async=1,i.src=n,c.parentNode.insertBefore(i,c)
}(window,document,"script",ALGOLIA_INSIGHTS_SRC,"aa");
</script>
```
and when the library is loaded, when `instance` …
> fix(bundle): return instance from browser bundle and fix e2e test

- lib/__tests__/init.test.ts
- lib/_cookieUtils.ts
This PR updates `onUserTokenChange` so that when it receives `undefined`, then it can clear the previous callback and won't throw any exceptions.
Before this, the following code threw an exception:
```js
analyticsInstance.onUserTokenChange(undefined, { immediate: true });
```
> fix(userToken): let user clear the callback for userToken

- lib/__tests__/get.test.ts
- lib/__tests__/harvest.test.ts
- lib/get.ts
- lib/insights.ts
This PR adds a method `_get` for internal usage.
Currently we cannot get the instance variables because the main interface is a function (`aa()`).
The initial reason for this functionality is because I need access to `_hasCredentials`.
The reason why I didn't make this function return a value, but make it accept a callback is,
it won't work in umd build.
```js
!function(e,a,t,n,s,i,c){e.AlgoliaAnalyticsObject=s,e[s]=e[s]||function(){
(e[s].queue=e[s].queue||[]).push(arguments)},i=a.createElement(t),c=a.getElementsByTagName(t)[0],
i.async=1,i.src=n,c.parentNode.insertBefore(i,c)
}(window,document,"script",ALGOLIA_INSIGHTS_SRC,"aa");
```
According to the snippet,
`window.aa` is basically a function adding commands to the queue.
```js
function () {
(e[s].queue = e[s].queue || …
```
> feat(get): add _get function

- empty-module.cjs.js
- package.json
React Native's packager (Metro) will parse all files for dependencies, and will throw an error for missing dependencies, even if they are not used or in a try-catch
see: https://github.com/facebook/react-native/issues/5079
> feat(react-native): shim native node modules

- README.md
- package.json
- ship.config.js
- yarn.lock
This PR updates Ship.js to the latest version (using `npm publish` instead of `yarn publish`).
> chore(release): update shipjs to the latest version

- lib/__tests__/init.test.ts
- lib/init.ts
This PR follows `userHasOptedOut` a step further.
Even with `userHasOptedOut: true`, search-insights created anonymous user token and stored it in the cookie, which is totally not used at all. (I'm not talking about the possibility of that customers could've read that cookie directly for some reason)
In my opinion, this shouldn't be treated as a breaking change. What do you think?
---
ps. I put the people I recently talked about this with as reviewers.
> fix: do not store anonymous token in cookie when user has opted out

- lib/__tests__/_getFunctionalInterface.test.ts
- lib/_getFunctionalInterface.ts
This PR adds a warning message about unknown function name. It used to just ignore unknown function names, which made it hard to notice when mistakes were made.
> fix: warn about unknown function name

- README.md
- lib/__tests__/init.test.ts
- lib/init.ts
This PR makes it accept `userToken` parameter at `init()` method, which enables users to initialize the insights client with the initial user token.
If it's given, it will not set anonymous user token in the cookie.
related: https://github.com/algolia/instantsearch.js/pull/4608
> feat(init): accept userToken at init() method

- .gitignore
- empty-module.cjs.d.ts
- index-browser.cjs.d.ts
- index-node.cjs.d.ts
- lib/typings.d.ts
- package.json
- tsconfig.declaration.json
- tsconfig.json
Related to this issue: https://github.com/algolia/search-insights.js/issues/9
- Type definitions are now emitted to the `./dist` folder using `tsc`.
- Types are now included in the tarball when running `npm publish` or `npm pack`.
> fix(types): emit and publish type definitions to npm

- index-node.cjs.d.ts
**Summary**: `index-node.cjs.d.ts` does not have a default export, making the [usage in the docs](https://github.com/microsoft/TypeScript/issues/2726) throw type error import has no call signature. Reexport the default
**Problem**: file `index-node.cjs.d.ts` simply `export *` from file `./dist/entry-node-cjs`. `entry-node-cjs.d.ts` have a default export but `export *` does not let the default export flow through as described by [TypeScript issue 2726](https://github.com/microsoft/TypeScript/issues/2726)
```javascript
window.aa('init', {})
^^^^^^^^^^^
// this gives a type error as the library doesn't have a default export and therefore no callable signature
// however the code still runs 
```
**Solution**: explicitly reexport the default
> Explicitly export default

- README.md
- examples/instantsearch/instantsearch.html
- examples/instantsearch/product.html
- lib/__tests__/harvest.test.ts
- lib/__tests__/init.test.ts
- lib/init.ts
This PR make `useCookie` `false` by default.
BREAKING CHANGE: It used to be `true`, but to be GDPR compliant, we're changing it to `false` by default.
For your information, this PR will be merged to `next` (not `master`).
Once it's ready to release the next major version, we will create a PR to merge `next` into `master`.
> fix(cookie): make useCookie false by default

- lib/__tests__/init.test.ts
- lib/init.ts
This PR prevents anonymous user token overriding an existing token.
It happens only when `init()` is called multiple times.
```js
aa('init', { appId, apiKey }); // this sets anonymous user token
aa('setUserToken', 'my-token');
aa('init', { appId, apiKey }); // this sets anonymous user token again and overrides 'my-token'
```
This prevents the side effect of calling `init()` multiple times.
An alternative solution is to skip `init()` calls if it was already initialized, but I'm not sure if that's a correct behavior.
> fix(userToken): prevent anonymous user token from overriding existing token

- index-browser.cjs.d.ts
- index-node.cjs.d.ts
This PR exports the type of the default function.
[This sandbox](https://codesandbox.io/s/2inzf?file=/index.ts) shows this error
This PR fixes it. ([See →](https://codesandbox.io/s/search-insights-test-in-parcel-forked-56994?file=/index.ts))
> fix(types): export default

- lib/__tests__/harvest.test.ts
- lib/_getVersion.ts
- lib/insights.ts
- lib/types.ts
This PR adds `getVersion` method. So far, we've had `version` property in the `AlgoliaAnalytics` class but never exposed a getter method.
In InstantSearch.js, we need this to ensure if the insights middleware is being used with the compatible version of search-insights.
> feat: add getVersion method

- lib/_getFunctionalInterface.ts
- lib/click.ts
- lib/types.ts
This PR updates the type `InsightsClient`. When the second parameter was wrong, TypeScript gave unhelpful error messages. With this change, now it can infer which method is being used, and thus provide better error messages about the second parameter.
fixes: #268
* sandbox: https://codesandbox.io/s/insights-typing-issue-with-clickedobjectidsaftersearch-forked-wzbon?file=/src/index.ts
---
```js
insights("init", { appId, apiKeyy: "aaa" });
```
```js
insights("clickedObjectIDsAfterSearch", {
userToken: "user-1",
eventName: "your_event_name",
index: "your_index_name",
// queryID: "queryID",
objectIDs: ["objectID1", "objectID2"],
positions: [17, 19]
});
```
```js
insights('unknown_method');
```
Now it infers the method and provide error messages for that specific method.
> fix(types): provide better error messages for insights client

- lib/_sendEvent.ts
- lib/conversion.ts
This PR adds `eventName` to `InsightsSearchConversionEvent`. It was missing.
> fix(types): make eventName required

- lib/entry-browser-cjs.ts
- lib/entry-node-cjs.ts
This PR removes
- `getRequesterForNode` from `entry-browser-cjs`
- `getRequesterForBrowser` from `entry-node-cjs`
They seem unnecessary.
It also breaks React Native (#319). It resolves `entry-browser-cjs` but it tries to resolve all the dependencies regarding `getRequesterForNode`, and fails.
This may be seen as a breaking change, but I doubt if there's any case where they resolve `entry-browser-cjs` AND need requester for node. Feel free to create an issue for discussion if you have such needs.
> fix(bundle): remove unnecessary exports from bundles

- lib/__tests__/_sendEvent.test.ts
- lib/utils/__tests__/request.test.ts
- lib/utils/request.ts
`sendBeacon` can return `false` if it fails to add the request to the browser queue.
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon#return_values
In that case, we need to send the event in different way, otherwise we lose it. So we fall back to XHR if `sendBeacon` returns `false`.
> fix: fall back to XHR if sendBeacon returns false

- lib/__tests__/_sendEvent.node.test.ts
- lib/__tests__/_sendEvent.test.ts
- lib/__tests__/click.test.ts
- lib/__tests__/conversion.test.ts
- lib/__tests__/view.test.ts
- lib/_addEventType.ts
- lib/_sendEvent.ts
- lib/click.ts
- lib/conversion.ts
- lib/insights.ts
- lib/types.ts
- lib/view.ts
- package.json
This PR enables sending multiple events in a single request.
search-insights has not supported sending multiple events, although [the REST API](https://www.algolia.com/doc/rest-api/insights/#push-events) already does.
- viewedObjectIDs
- viewedFilters
- clickedObjectIDsAfterSearch
- clickedObjectIDs
- clickedFilters
- convertedObjectIDsAfterSearch
- convertedObjectIDs
- convertedFilters
The methods above now can take multiple event payloads as arguments.
Also `sendEvent` method that used to be `protected` is now `public`. Its signature has changed, but it was never documented and an internal method, so I don't consider this a breaking change.
> feat: support multiple events

- .circleci/config.yml
- ship.config.js
This PR schedules release every Tuesday 11am (Paris time). It doesn't automatically releases the new version, but just calls `shipjs prepare` to create a release pull-request.
> chore: schedule release

- lib/__tests__/_algoliaAgent.test.ts
- lib/_algoliaAgent.ts
- lib/_sendEvent.ts
- lib/init.ts
- lib/insights.ts
This PR removes `_uaURIEncoded`, and uri-encodes it right before sending events. Previously it was a string being concatenated as new bits were added. Now it's an array, and gets joined with `;` later on.
> refactor: uri-encode user agent right before sending events

- README.md
This PR updates the README regarding `onUserTokenChange`.
The previous one was valid until search-insights@1, but not anymore since v2.
> docs: fix README regarding onUserTokenChange

- lib/__tests__/_algoliaAgent.test.ts
- lib/__tests__/_sendEvent.node.test.ts
- lib/__tests__/_sendEvent.test.ts
- lib/_algoliaAgent.ts
- lib/init.ts
- lib/typings.d.ts
- package.json
- rollup.config.js
This PR adds library flavor as algolia agent.
A global variable `__FLAVOR__` is added (`node-cjs` in dev mode), and is replaced at build time.
With this addition, we can get _insights_ on how many people are using which flavor of search-insights.
**Flavors:**
- browser-umd
- browser-cjs
- browser-iife
- node-cjs
**Example:**
Open [the sandbox](https://codesandbox.io/s/vanilla-forked-ol43i?file=/src/index.js) and see the network panel.
> chore: add library flavor to algolia agent

- lib/__tests__/_sendEvent.test.ts
- lib/_sendEvent.ts
- package.json
This PR encodeURIComponent filter values.
> fix: encodeURIComponent filters

- lib/utils/__tests__/request.test.ts
- lib/utils/request.ts
React Native for Android wasn't setting a `Content-Type` header and requests were failing silently since we don't set the `XMLHttpRequest.onerror` callback.
For this second point, I'll create an issue, and we should discuss about what's the right way to handle this by default.
> fix: add default `Content-Type` and `Content-Length` headers to `XMLHttpRequest` instance

- examples/instantsearch/instantsearch.html
- examples/instantsearch/product.html
- lib/__tests__/_createInsightsClient.test.ts
- lib/_createInsightsClient.ts
- lib/entry-umd.ts
- lib/insights.ts
This allows us to detect a search-insights instance, regardless of whether it's using umd or cjs entry points.
FX-2264
> feat(api): expose window.AlgoliaAnalyticsObject if not yet set

- README.md
- lib/__tests__/init.test.ts
- lib/init.ts
This introduces a ~~`patch`~~ `partial` option in the `init` method which lets you update only the options that you declare, without resetting the others.
If this works for us, we can backport this in v1, and have it implemented in the upcoming v3.
> feat(v2): allow to `init` again while preserving passed options

- README.md
- lib/__tests__/init.test.ts
- lib/init.ts
- package.json
This introduces a `partial` option in the `init` method which lets you update only the options that you declare, without resetting the others.
Related: https://github.com/algolia/search-insights.js/pull/401
> feat(v1): allow to `init` again while preserving passed options

- ship.config.js
Quick PR to attribute the correct reviewer group to ShipJS release pull requests, which in its current state throws an error during the prepare process.
> chore: update reviewers for shipjs release pr

- lib/__tests__/_createInsightsClient.test.ts
- lib/_createInsightsClient.ts
- lib/entry-umd.ts
- lib/types.ts
This PR exposes a `version` property on the functional interface that is provided either through UMD or CJS bundles.
Combined with an updated snippet that also provides this in the temporary queue structure, it will help consumers reliably determine the version of the search-insights library before it is even loaded (in the case of UMD).
> feat: expose version string from functional interface

- lib/__tests__/_sendEvent.test.ts
- lib/__tests__/harvest.test.ts
- lib/__tests__/init.test.ts
- lib/_sendEvent.ts
- lib/_tokenUtils.ts
- lib/init.ts
- lib/insights.ts
This PR allows to `init` without credentials (`appId` and `apiKey`).
You can now pass credentials directly when sending events, so it's not always necessary to set credentials when calling `init`.
- `init` can be called without `options`, an empty `options` object or defined `options`.
- `sendEvents` will now throw an error if no credentials coming from `init` or custom ones (coming from `additionalParams`) are provided.
- `partial: true` can be used to update `appId` and/or `apiKey`.
> feat: allow to `init` without credentials (v2)

- README.md
- lib/__tests__/_sendEvent.test.ts
- lib/__tests__/get.test.ts
- lib/__tests__/harvest.test.ts
- lib/__tests__/init.test.ts
- lib/_initSearch.ts
- lib/_sendEvent.ts
- lib/_tokenUtils.ts
- lib/init.ts
- lib/insights.ts
[FX-2282](https://algolia.atlassian.net/browse/FX-2282)
This PR makes `init` optional as you can already pass credentials directly when sending events using `sentEvent`, so it's not always necessary to set credentials when calling `init`.
- `init` can be called without `options`, an empty `options` object or defined `options`.
- `sendEvent` will now throw an error if no credentials coming from `init` or custom ones (coming from `additionalParams`) are provided.
- `partial: true` can be used to update `appId` and/or `apiKey`.
- update the README to reflect the changes.
[FX-2282]: https://algolia.atlassian.net/browse/FX-2282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: make `init` optional (v1)

- pre-deploy.sh
The pre-deploy script checks for the presence of a local reporting address to determine whether the library has been built correctly or not. Recent developments made this script check fail as now there are 2 occurrences of this reporting address.
This PR only retrieve the first occurrence as only one is needed to make the assertion.
> ci: fix pre-deploy script

- ship.config.js
This PR changes the Ship.js config so that future releases of search-insights@v1 are tagged `latest-1.x` on npm, instead of polluting the `latest` tag which should be left for the actual latest version of the library.
> ci: npm publish to branch-specific latest tag

- README.md
- lib/__tests__/init.test.ts
- lib/init.ts
- lib/insights.ts
Backport the `host` option submitted by a customer.
Fix `_endpointOrigin` being overwritten when using init with the `partial` option (region was not being preserved).
> feat: add host option

- lib/__tests__/_sendEvent.node.test.ts
- lib/__tests__/_sendEvent.test.ts
- lib/_sendEvent.ts
- lib/_tokenUtils.ts
- lib/init.ts
- lib/insights.ts
This PR introduces a new initialization parameter: `anonymousUserToken`. This boolean (set to `true` by default) generates an in-memory anonymous user token which is sent with every Insights event.
See [FX-2303](https://algolia.atlassian.net/browse/FX-2303) for more information.
[FX-2303]: https://algolia.atlassian.net/browse/FX-2303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(userToken): generate in-memory anonymous user tokens by default

- README.md
This PR makes sure the default snippets we show on the README reference the version that supports automatic insights and include the `<aa>.version` property that allows libraries to reliably identify them.
> chore: update readme snippets

- package.json
Not really sure how this happened, but this https://github.com/algolia/search-insights.js/pull/374 seems to been accidentally reverted.
> chore: update package owner

- package.json
This config is a warning at best and only enforced if https://docs.npmjs.com/cli/v9/using-npm/config#engine-strict is set.
Our node version requirements are for building and testing the package, rather than actually running the code.
CR-4263
> fix: remove engines config from package.json

- lib/types.ts
The new conversion subtypes added a top level value and currency attribute to the event object, as well as allowing a queryID to be provided via the objectData.
EEX-703
> fix: add missing type defs for conversion subtypes

- .circleci/config.yml
Hey team 👋 , I got notified of a pipeline fail in the release process for this repository. 
This is due to newer versions of Shipjs creating annotated tags, which require git credentials.
This PR sets up a dummy Git user to allow Shipjs to correctly perform post release tasks: git tag creation and github release publication. This should allow next releases to be run more smoothly.
> chore(ci): setup git user for shipjs post-release tasks

- docs/nodejs.md
- lib/__tests__/_sendEvent.test.ts
- lib/__tests__/_tokenUtils.test.ts
- lib/__tests__/init.test.ts
- lib/_sendEvent.ts
- lib/_tokenUtils.ts
- lib/click.ts
- lib/conversion.ts
- lib/init.ts
- lib/insights.ts
- lib/types.ts
- lib/view.ts
* Add `authenticatedUserToken` field to event types
* Add `setAuthenticatedUserToken` method to enable users to set the field to be automatically passed in subsequent `sendEvent` calls
* Add `getAuthenticatedUserToken` method to enable users to get the `authenticatedUserToken` field
* Add `onAuthenticatedUserTokenChange` to enable passing a callback on `authenticatedUserToken` change
* Enable `authenticatedUserToken` to be passed on `init`
[EEX-746](https://algolia.atlassian.net/browse/EEX-746)
More context:
* [Insights user identity proposal (Confluence)](https://algolia.atlassian.net/wiki/spaces/PREDICT/pages/4559470786/Insights+user+identity+proposal)
* [Authenticated user token in Insights pipeline (Confluence)]( https://algolia.atlassian.net/wiki/spaces/EX/pages/4576346340/2023-05-25+ …
> feat: add support for authenticatedUserToken

- jest.setup.js
- lib/utils/__tests__/featureDetection.node.test.ts
- lib/utils/__tests__/request.test.ts
- lib/utils/featureDetection.ts
- lib/utils/getRequesterForBrowser.ts
- lib/utils/getRequesterForNode.ts
- lib/utils/request.ts
- package.json
- yarn.lock
First of all, thank you for maintaining the great library!
As described in issue #444, importing `search-insights` on an '[edge-runtime](https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes)' results in the following error: 
`[Error: Could not find a supported HTTP request client in this environment.]`
The edge runtime however, does [support `fetch`](https://nextjs.org/docs/pages/api-reference/edge) (and is added to node [per version 18](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch)).
This PR adds a fallback to the native `fetch` method when nodeHttpRequest is not available.
Please let me know if you'd like to see anything changed :-).
Kind regards.
> feat: introduce native fetch fallback when http-module is not supported

- lib/__tests__/_tokenUtils.test.ts
- lib/__tests__/init.test.ts
- lib/_tokenUtils.ts
Users may want to unset the authenticated user token, for example, when a user logs out.
[EEX-836](https://algolia.atlassian.net/browse/EEX-836)
[EEX-836]: https://algolia.atlassian.net/browse/EEX-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: enable unsetting authenticatedUserToken

- lib/__tests__/conversion.test.ts
- lib/conversion.ts
Create distinct type for `purchase` event parameters - same as a normal `conversion` event but the top-level `queryID` is optional and deprecated.
[EEX-808](https://algolia.atlassian.net/browse/EEX-808)
[EEX-808]: https://algolia.atlassian.net/browse/EEX-808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: deprecate purchase event top-level queryID param

- lib/__tests__/conversion.test.ts
- lib/conversion.ts
Add ecommerce `value` property to conversion events as specified in the [Insights Update spec](https://algolia.atlassian.net/wiki/spaces/EX/pages/4652531940/Insights+update#Purchase)
[EEX-886](https://algolia.atlassian.net/browse/EEX-886)
[EEX-886]: https://algolia.atlassian.net/browse/EEX-886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add value property to conversion events

- lib/__tests__/conversion.test.ts
- lib/conversion.ts
The [previous change](https://github.com/algolia/search-insights.js/pull/526) only applied to 'after search' events
> feat: add value property to non-search-related conversion events

- lib/__tests__/_sendEvent.test.ts
- lib/_sendEvent.ts
When the events payload is empty don't bother sending the request, fail fast.
> feat: fast fail when sending no events

- lib/__tests__/_addQueryId.test.ts
- lib/__tests__/_sendEvent.test.ts
- lib/__tests__/click.test.ts
- lib/_addQueryId.ts
- lib/_sendEvent.ts
- lib/click.ts
- lib/types.ts
- lib/utils/__tests__/localStorage.test.ts
- lib/utils/__tests__/objectQueryTracker.test.ts
- lib/utils/index.ts
- lib/utils/localStorage.ts
- lib/utils/objectQueryTracker.ts
- package.json
This is the majority of the inference logic. A couple of things not added yet:
* when `eventSubtype` is `addToCart` store any queryID passed for future `purchase` conversion events
* removal of objectID/queryID association from store when `eventSubtype` is `purchase`
* pruning of associations older than 90 days
> feat: add query id inference for conversion events based on prior clicks

- lib/__tests__/_algoliaAgent.test.ts
- lib/__tests__/_sendEvent.node.test.ts
- lib/__tests__/_sendEvent.test.ts
- lib/__tests__/conversion.test.ts
- lib/__tests__/integrationTests.test.ts
- lib/_sendEvent.ts
- lib/conversion.ts
- lib/utils/__tests__/index.test.ts
- lib/utils/__tests__/localStorage.test.ts
- lib/utils/__tests__/objectQueryTracker.test.ts
- lib/utils/index.ts
- lib/utils/localStorage.ts
- lib/utils/objectQueryTracker.ts
- package.json
Added the remaining logic to:
* store any queryID passed for future `purchase` conversion events when `eventSubtype` is `addToCart`
* remove objectID/queryID association from store when `eventSubtype` is `purchase`
* keep most recent 4,000 associations when store reaches 5,000
> feat: query id inference pruning of purchased and oldest associations when limit is reached

- lib/utils/__tests__/request.test.ts
- lib/utils/request.ts
Setting the `Content-Length` request header in the context of an XMLHttpRequest leads to the error:
```
Refused to set unsafe header "Content-Length"
```
This header is considered a forbidden request header that can't be set with `setRequestHeader()`. I've confirmed that the initial implementation was unnecessary: https://github.com/algolia/search-insights.js/pull/358#issuecomment-2324026184.
See the XMLHttpRequest specs:
* [setRequestHeader() method](https://xhr.spec.whatwg.org/#the-setrequestheader()-method)
* [Forbidden request header](https://fetch.spec.whatwg.org/#forbidden-request-header)
[CR-6763](https://algolia.atlassian.net/browse/CR-6763)
[CR-6763]: https://algolia.atlassian.net/browse/CR-6763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
> fix: don't set Content-Length in XMLHttpRequest fn

- lib/__tests__/init.test.ts
- lib/_tokenUtils.ts
- lib/init.ts
- lib/insights.ts
In InstantSearch, in order for user tokens to be set in time for the first query on page load, anonymous user tokens are generated and set as both the InstantSearch token and Insights token.
This flow has one issue though. When `useCookies` flag needs to be changed later (such as with a cookie consent banner), a second `init` call to insights with the flag set to true does not save the existing token to a cookie.
A short repro is as follows with the very latest version of InstantSearch where this behaviour was added (PR: https://github.com/algolia/instantsearch/pull/6377):
```js
const searchClient = algoliasearch(
// ...
);
window.aa('init', {
appId: 'id',
apiKey: 'key',
});
const search = instantsearch({
indexName: 'index',
searchClient,
insights: true,
});
search.addWidgets([
// ...
]); …
```
> fix: save existing anon tokens for multiple init calls 

- lib/init.ts
Remove unnecessary `console.log` message from `algolia/search-insights`, which stated:
"Since v2.0.4, search-insights no longer validates event payloads."
This message appeared in dev mode and is no longer needed (as it's over 2 years old by now)
> cleanup: remove unnecessary console.log in dev
