algolia/search-insights.js

examples/async/async.js
examples/autocomplete/autocomplete.js
examples/helper/helper.js
examples/instantsearch/instantsearchExample.js
examples/lunr/lunr.js
examples/react-instantsearch/src/App.js
examples/vue-instantsearch/src/App.vue
lib/__tests__/_sendEvent.test.ts
lib/__tests__/click.test.ts
lib/__tests__/harvest.test.ts
lib/_sendEvent.ts
lib/click.ts
lib/conversion.ts
lib/insights.ts
lib/utils/index.test.ts
lib/utils/index.ts
package.json
tests/data.txt
yarn.lock

This PR adds to sendEvent everything it needs to make search related tracking (click and conversion)

feat(v2): implement search params in sendEvent

---

lib/__tests__/_sendEvent.test.ts
lib/__tests__/click.test.ts
lib/__tests__/conversion.test.ts
lib/click.ts
lib/conversion.ts

- objectID -> objectIDs
- position -> positions
- removed queryID magic in conversion

fix(payload): objectIDs, positions, queryID

---

lib/__tests__/_sendEvent.test.ts
lib/__tests__/harvest.test.ts
lib/_cookieUtils.ts
lib/_sendEvent.ts
lib/click.ts
lib/conversion.ts
lib/insights.ts
lib/view.ts

endpoint now is expects userToken instead of userID.
This is a simple search and replace over all the code base

fix(userToken): migrate userID => userToken

---

lib/__tests__/_sendEvent.test.ts
lib/__tests__/click.test.ts
lib/__tests__/conversion.test.ts
lib/_sendEvent.ts
lib/conversion.ts

fix(tests): fixed the test name

---

lib/_sendEvent.ts

My mistake, I forgot to add this event type

fix(types): add InsightEventType 'view'

---

examples/async/async.js
examples/helper/helper.js
examples/instantsearch/instantsearchExample.js
examples/lunr/lunr.js
examples/react-instantsearch/src/App.js
lib/__tests__/click.test.ts
lib/__tests__/conversion.test.ts
lib/click.ts
lib/conversion.ts
lib/insights.ts

fix(naming): various name fixes

---

examples/async/async.js
examples/helper/helper.js
examples/instantsearch/instantsearchExample.js
examples/lunr/lunr.js
examples/react-instantsearch/src/App.js
examples/vue-instantsearch/src/App.vue
lib/__tests__/_sendEvent.test.ts
lib/__tests__/click.test.ts
lib/__tests__/conversion.test.ts
lib/__tests__/harvest.test.ts
lib/__tests__/init.test.ts
lib/__tests__/view.test.ts
lib/_cookieUtils.ts
lib/_sendEvent.ts
lib/click.ts
lib/conversion.ts
lib/init.ts
lib/insights.ts
lib/view.ts
rollup.config.js

This is what happens when mock stuff :)

fix(payload): indexName -> index

---

lib/__tests__/_cookieUtils.test.ts
lib/__tests__/init.test.ts
lib/_cookieUtils.ts
lib/_sendEvent.ts
lib/init.ts
lib/insights.ts
lib/utils/index.test.ts
lib/utils/index.ts

This PR:
- adds cookieDuration param to init
- check it's a valid integer
- and uses it to computed the expire date of the cookie

feat(cookieDuration): add cookieDuration support

---

lib/__tests__/_sendEvent.test.ts
lib/_sendEvent.ts

⚠️ ~awaiting support for X-Algolia-Agent URL param https://github.com/algolia/go/pull/1189~ it's been merged

feat(UserAgent): add user agent string

---

lib/__tests__/_sendEvent.test.ts
lib/__tests__/harvest-async.test.ts
lib/__tests__/init.test.ts
lib/_cookieUtils.ts
lib/_sendEvent.ts
lib/conversion.ts
lib/init.ts

Theses are fixes I've made on the go while working on react-native compat.
They are small enough that I grouped them in a single PR.

fix(typos): various minor unrelated fixes 

---

lib/__tests__/_algoliaAgent.test.ts
lib/_algoliaAgent.ts
lib/_sendEvent.ts
lib/init.ts
lib/insights.ts

This introduces a addAlgoliaAgent method that can be also found in the
search client.
```ts
aa('addAlgoliaAgent', 'a random string')
```

feat(UserAgent): introduce addAlgoliaAgent method

---

config/webpack.config.js

This PR adds an error message when there are missing environment variables.

chore: add error message when missing env variable

---

package.json

This PR adds a minimum node version to `package.json`.

chore: add minimum node version

---

lib/__tests__/harvest.test.ts

This PR adds e2e tests for `setUserToken` and cookie. It is not adding any feature.

test(setUserToken): check setUserToken and cookie behaviour

---

lib/click.ts
lib/conversion.ts

This follows up on a review left by @samouss
https://github.com/algolia/search-insights.js/pull/35#discussion_r240576470
It closes https://github.com/algolia/search-insights.js/issues/54

chores: improve comments for {clicked,converted}ObjectIDs

---

package.json

This PR updates the `description` field in `package.json` file to better introduce search-insights.js.
(discussed in the slack)

chore: update description in package.json

---

lib/_getFunctionalInterface.ts
lib/entry-browser-cjs.ts
lib/entry-node-cjs.ts
lib/types.ts

This PR exposes the types of the public methods.

fix(types): expose the types of public methods

---

README.md

This PR updates the v2 banner to include v1 doc link and an emoji to make it more noticeable.

docs: update v2 banner

---

README.md

typos: fix version number for iife build in readme

---

package.json

chore(author): change to Algolia

---

README.md
lib/__tests__/_sendEvent.test.ts
lib/__tests__/click.test.ts
lib/__tests__/conversion.test.ts
lib/__tests__/view.test.ts
lib/_sendEvent.ts
lib/click.ts
lib/conversion.ts
lib/insights.ts
lib/types.ts
lib/view.ts
package.json

See https://github.com/algolia/search-insights.js/pull/398

feat: pass custom credentials as additional arguments of insights methods (v1)

---

README.md
examples/instantsearch/instantsearch.html
examples/instantsearch/instantsearchExample.js
examples/instantsearch/product.html
lib/__tests__/_sendEvent.test.ts
lib/__tests__/click.test.ts
lib/__tests__/conversion.test.ts
lib/__tests__/view.test.ts
lib/_sendEvent.ts
lib/click.ts
lib/conversion.ts
lib/types.ts
lib/utils/__tests__/extractAdditionalParams.test.ts
lib/utils/extractAdditionalParams.ts
lib/utils/index.ts
lib/view.ts

See https://github.com/algolia/search-insights.js/pull/398

feat: pass custom credentials as additional arguments of insights methods (v2)

---

ship.config.js

chore: update reviewers for shipjs release pr

---

lib/__tests__/_createInsightsClient.test.ts
lib/_createInsightsClient.ts
lib/entry-umd.ts
lib/types.ts
package.json

feat: expose version string from functional interface

---

lib/__tests__/init.test.ts
lib/init.ts

solution for: https://support.algolia.com/hc/en-us/requests/545695

feat(api): add host to the initial params

---

README.md

This updates the code snippet to account for the version.

fix(v1): update code snippet to reflect version

---

lib/__tests__/_tokenUtils.test.ts
lib/__tests__/harvest.test.ts
lib/_algoliaAgent.ts
lib/_createInsightsClient.ts
lib/_getVersion.ts
lib/_processQueue.ts
lib/_sendEvent.ts
lib/_tokenUtils.ts
lib/click.ts
lib/conversion.ts
lib/init.ts
lib/insights.ts
lib/polyfills/objectAssign.ts
lib/polyfills/objectKeys.ts
lib/types.ts
lib/utils/index.ts
lib/utils/request.ts
lib/view.ts
package.json
tsconfig.json

I found that this makes the codebase easier to navigate and allows the type system to catch potential errors.

Improve use of types and increase strictness

---

lib/__tests__/_getFunctionalInterface.test.ts
lib/__tests__/_sendEvent.test.ts
lib/__tests__/_tokenUtils.test.ts
lib/__tests__/click.test.ts
lib/__tests__/conversion.test.ts
lib/__tests__/harvest.test.ts
lib/__tests__/init.test.ts
lib/__tests__/view.test.ts
lib/utils/__tests__/request.test.ts
lib/utils/request.ts
package.json
yarn.lock

This will enable being able to `await` on events being sent.

feat(request): enable requests to be awaited upon

---

ship.config.js

As per https://github.com/algolia/search-insights.js/pull/490#discussion_r1310172581

chore: update ship.js config

---

index-node.mjs
package.json
rollup.config.mjs

Fixes "Module not found: Default condition should be last one." errors when using Next.js

fix: correct order of exports

---

index-node.cjs
lib/entry-browser.ts
lib/entry-node.ts
lib/utils/__tests__/localStorage.test.ts
lib/utils/localStorage.ts
lib/utils/request.ts

fix: test for localStorage before using it and enable it to be shimmed with a Storage-compatible interface

---

lib/__tests__/_getFunctionalInterface.test.ts
lib/_getFunctionalInterface.ts
lib/_getVersion.ts
lib/_sendEvent.ts
lib/types.ts

feat: update getFunctionalInterface to return the method being passed instead of just executing

---

lib/__tests__/click.test.ts
lib/__tests__/conversion.test.ts
lib/click.ts
lib/conversion.ts

[EEX-1348](https://algolia.atlassian.net/browse/EEX-1348)
[EEX-1348]: https://algolia.atlassian.net/browse/EEX-1348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: don't store query/object associations when userHasOptedOut is true

---

lib/utils/localStorage.ts
package.json

[EEX-1349](https://algolia.atlassian.net/browse/EEX-1349)
Fixes #556.
[EEX-1349]: https://algolia.atlassian.net/browse/EEX-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: check if localStorage is usable before using it
